# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################
Organizations:
    - &phangiathuyend4f2
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: phangiathuyend4f2MSP

        # ID to load the MSP definition as
        ID: phangiathuyend4f2MSP

        MSPDir: ../organizations/peerOrganizations/phangiathuyend4f2.example.com/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('phangiathuyend4f2MSP.admin', 'phangiathuyend4f2MSP.peer', 'phangiathuyend4f2MSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('phangiathuyend4f2MSP.admin', 'phangiathuyend4f2MSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('phangiathuyend4f2MSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('phangiathuyend4f2MSP.peer')"
