# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################
Organizations:
    - &gfgfgdfgdfgf
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: gfgfgdfgdfgfMSP

        # ID to load the MSP definition as
        ID: gfgfgdfgdfgfMSP

        MSPDir: ../organizations/peerOrganizations/gfgfgdfgdfgf.example.com/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('gfgfgdfgdfgfMSP.admin', 'gfgfgdfgdfgfMSP.peer', 'gfgfgdfgdfgfMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('gfgfgdfgdfgfMSP.admin', 'gfgfgdfgdfgfMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('gfgfgdfgdfgfMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('gfgfgdfgdfgfMSP.peer')"
