# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################
Organizations:
    - &phangiathuyendevfs3dsdfe
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: phangiathuyendevfs3dsdfeMSP

        # ID to load the MSP definition as
        ID: phangiathuyendevfs3dsdfeMSP

        MSPDir: ../organizations/peerOrganizations/phangiathuyendevfs3dsdfe.example.com/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('phangiathuyendevfs3dsdfeMSP.admin', 'phangiathuyendevfs3dsdfeMSP.peer', 'phangiathuyendevfs3dsdfeMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('phangiathuyendevfs3dsdfeMSP.admin', 'phangiathuyendevfs3dsdfeMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('phangiathuyendevfs3dsdfeMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('phangiathuyendevfs3dsdfeMSP.peer')"
